# © [2005] [KingIT Solutions (Pvt) Ltd]. All Rights Reserved. 2025-03-19



name: Add Copyright Header

on:
  push:
    branches:
      - "**"

jobs:
  add-copyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use a Personal Access Token for permission

      - name: Check if commit is from GitHub Actions
        run: |
          if git log -1 --pretty=%an | grep -q "github-actions"; then
            echo "Commit is from GitHub Actions, skipping workflow."
            exit 0
          fi

      - name: Run copyright header script
        run: |
          chmod +x .github/scripts/add_copyright.sh
          .github/scripts/add_copyright.sh

      - name: Commit changes if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git commit -am "chore: add copyright header [skip ci]"
            git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
          else
            echo "No changes needed"
          fi
