name: Add Copyright Header

on:
  push:
    branches:
      - dev

jobs:
  add-copyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use PAT for permission

      - name: Run copyright header script
        run: |
          chmod +x .github/scripts/add_copyright.sh
          .github/scripts/add_copyright.sh

      - name: Commit changes if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git commit -am "chore: add copyright header"
            git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
          else
            echo "No changes needed"
          fi
